### ISSUE TITLE
Milestone 1 : Setup Kanban board

### ISSUE THREAD

**Issue by Chrissiku** [Chrissiku/Space-x#25]
## Space-x group project
> Project link : https://github.com/Chrissiku/Space-x/
> Project board: https://github.com/Chrissiku/Space-x/projects/1

_[_NOTE_]: This project will be done by a team of 2 people listed below_
### Team members
- Member one : [Chris Siku](https://github.com/Chrissiku/)
- Member two : [Grayce Muthui](https://github.com/Graycemuthui/)

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @Chrissiku and @Graycemuthui,

Your project is complete!  There is nothing else to say other than... it's time to go ahead with the project :shipit: 
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Chrissiku** [comment]
Thank you @TedLivist
