### ISSUE TITLE
Team3 [1pt] Switch badges for Dragons - Conditional components

### ISSUE THREAD

**Issue by Chrissiku** [Chrissiku/Space-x#4]
Dragons that have already been reserved should show a "Reserved" badge and "Cancel reservation" button instead of the default "Reserve dragon" (as per design).

Use the React conditional rendering syntax:
```javascript
{rocket.reserved && ( 
    // render Cancel Rocket button
)}
```

**Comment by elidakirigo** [comment]
hi , I'd like to help you contribute in this issue if its still open, thanks
